{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPYouvmQqlVvnZZNr4bCD8E"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["#  Welcome to exception handling notebook\n","\n","In this notebook will introduce the concepts of exception handling.\n","\n","<br>\n","\n","## Table of content:\n","1. Try Except\n","1. Try Except Else\n","1. Try Except Finally\n","\n","<br>\n","\n","## Notebook structure (text cell sections):\n","- ***Explanation section:*** Explanation about the code cell below or logic implemented.\n","\n","- <font color='#118ab2'>***Theoretical section:***</font> Concept or theoretical explanation of the topic to be covered.\n","\n","- <font color='#ee6c4d'>***Quiz or challenge section:***</font> This could be a question about the behavior of line(s) of code or development for a specific logic or task.\n","\n","- <font color='#8DB580'>***Extra information section:***</font> Alternatives for any solutions, additional information or extra advice\n","\n","- <font color='#db3a34'>***Error section:***</font> Explanation of a common error and solution\n","\n","___"],"metadata":{"id":"Mmz38KmfRZWb"}},{"cell_type":"markdown","source":["# <font color='#118ab2'>***Exception Handling***</font>\n","\n","## What is a exception handling?\n","\n","Exception handling is the **process of detecting and responding to exceptional situations or errors** that occur during program execution. When an exception occurs, it disrupts the normal flow of a program and an error message is displayed. **Exception handling provides a mechanism to gracefully handle these exceptions and continue program execution without crashing.**\n","\n","Exception handling is important for writing robust and reliable programs. By handling exceptions, programs can continue to run even in the face of unexpected errors or user input.\n","\n","<br>\n","\n","### **Concept**\n","\n","![exception handling concept](https://www.edureka.co/blog/wp-content/uploads/2018/11/Exception-flow-Java-Exception-Handling-Edureka.png)\n","\n","### **Implementation**\n","\n","These exceptions are caught and handled using the `try-except` block. The `try` block contains the code that may raise an exception, and the `except` block contains the code that handles the exception. If an exception occurs, the code in the `try` block stops executing and the code in the except block is executed to handle the exception.\n","\n","<br>\n","\n","```python\n","  try:\n","      # code that may raise an exception\n","  except:\n","      # code to handle exception\n","```\n","\n","<br>\n","\n","### **Note**\n","> When handling exceptions, it is important to provide meaningful error messages to help with debugging.\n","\n","> It is generally a good practice to catch only the specific exceptions that you expect to be raised, rather than catching all exceptions.\n","\n","> It is also possible to raise your own exceptions using the `raise` keyword. This can be useful for indicating specific error conditions in your code."],"metadata":{"id":"rU-y05F6R5Ya"}},{"cell_type":"code","source":["print(\"Before exception\")\n","try:\n","    x = 1 / a\n","except:\n","    print(\"Division error\")\n","\n","print(\"After exception\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"kwTD8hJVSHKV","executionInfo":{"status":"ok","timestamp":1681786591120,"user_tz":360,"elapsed":170,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"7c2e802c-e48f-4cac-f8fb-ba6a465ba894"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Before exception\n","Division error\n","After exception\n"]}]},{"cell_type":"code","execution_count":2,"metadata":{"id":"ussc17PHQ-TE","colab":{"base_uri":"https://localhost:8080/","height":252},"executionInfo":{"status":"error","timestamp":1681786580159,"user_tz":360,"elapsed":205,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"f03ab953-d1d7-410e-bec6-ce49e022b837"},"outputs":[{"output_type":"stream","name":"stdout","text":["Before exception\n"]},{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-ae3d32622d53>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Before exception\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m     \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m1\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0ma\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Division by zero!\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mNameError\u001b[0m: name 'a' is not defined"]}],"source":["print(\"Before exception\")\n","try:\n","    x = 1 / a\n","except ZeroDivisionError:\n","    print(\"Division by zero!\")\n","\n","print(\"After exception\")"]},{"cell_type":"markdown","source":["## Common uses"],"metadata":{"id":"5XpJa3iIpa4F"}},{"cell_type":"markdown","source":["### Example 1"],"metadata":{"id":"OSwLUDuZqByq"}},{"cell_type":"code","source":["# Without Try Except\n","number_cast = input(\"Give me a number: \")\n","number_cast = float(number_cast)\n","print(number_cast)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":235},"id":"bFvba2MBpZd0","executionInfo":{"status":"error","timestamp":1681440316853,"user_tz":360,"elapsed":1870,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"b0c06f4d-6b49-448e-a853-8904b0b244d8"},"execution_count":null,"outputs":[{"name":"stdout","output_type":"stream","text":["Give me a number: a\n"]},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-90b4c97936d6>\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Without Try Except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mnumber_cast\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Give me a number: \"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mnumber_cast\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfloat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnumber_cast\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnumber_cast\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: could not convert string to float: 'a'"]}]},{"cell_type":"code","source":["# With Try Except\n","try:\n","  number_cast = input(\"Give me a number: \")\n","  number_cast = float(number_cast)\n","  print(number_cast)\n","except:\n","  print(\"Invalid number\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"e-iB5YCppyTI","executionInfo":{"status":"ok","timestamp":1681440371192,"user_tz":360,"elapsed":1023,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"bfdafd2d-a108-42c3-d708-608e9e6327de"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Give me a number: a\n","Invalid number\n"]}]},{"cell_type":"markdown","source":["### Example 2"],"metadata":{"id":"wTO-5Fu0qDt2"}},{"cell_type":"code","source":["# Without Try Except\n","list_example = [1,2,3]\n","find_number_index = list_example.index(4)\n","print(number_cast)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":217},"id":"ppa_EE4QqFfQ","executionInfo":{"status":"error","timestamp":1681440462389,"user_tz":360,"elapsed":4,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"0d2a59bc-10e5-4e2d-d3b7-38c3e0716f1d"},"execution_count":null,"outputs":[{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-f0e3a3e0fafd>\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Without Try Except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mlist_example\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mfind_number_index\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlist_example\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mindex\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnumber_cast\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: 4 is not in list"]}]},{"cell_type":"code","source":["# With Try Except\n","try:\n","  list_example = [1,2,3]\n","  find_number_index = list_example.index(4)\n","  print(number_cast)\n","except:\n","  print(\"The item is not in the list\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"cVTm0HytqFvI","executionInfo":{"status":"ok","timestamp":1681440640225,"user_tz":360,"elapsed":717,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"994a4c11-af1b-4363-e4d3-7164c2cc4966"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["The item is not in the list\n"]}]},{"cell_type":"markdown","source":["### Example 3"],"metadata":{"id":"5daIaOvLrMs8"}},{"cell_type":"code","source":["numerator = input(\"Enter the numerator: \")\n","denominator = input(\"Enter the denominator: \")\n","\n","# Print the error\n","try:\n","    result = int(numerator) / int(denominator)\n","    print(\"The result of \" + str(numerator) + \"/\" + str(denominator) + \" is \" + str(result))\n","except Exception as e:\n","    print(\"An error occurred:\", e)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"pesyl_dsrOff","executionInfo":{"status":"ok","timestamp":1681787101624,"user_tz":360,"elapsed":3180,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"7be0e1aa-4cf3-4b2b-dae4-2c0d85488990"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter the numerator: 1\n","Enter the denominator: a\n","An error occurred: invalid literal for int() with base 10: 'a'\n"]}]},{"cell_type":"markdown","source":["## <font color='#8DB580'>***Types of exception***</font>\n","\n","In Python, you can handle multiple types of exceptions in a single `try-except` block. This means that you can write multiple `except` blocks under a single `try` block to handle different types of exceptions.\n","\n","<br>\n","\n","#### Examples:\n","```python\n","  try:\n","    # some code that may raise exceptions\n","  except ValueError:\n","      # handle ValueError exception\n","  except ZeroDivisionError:\n","      # handle ZeroDivisionError exception\n","  except TypeError:\n","      # handle TypeError exception\n","  except:\n","      # handle any other exceptions\n","```\n","\n","<br>\n","\n","#### Code example"],"metadata":{"id":"IHj6XR7dsDcg"}},{"cell_type":"code","source":["numerator = input(\"Enter the numerator: \")\n","denominator = input(\"Enter the denominator: \")\n","\n","try:\n","    result = int(numerator) / int(denominator)\n","    print(\"The result of \" + str(numerator) + \"/\" + str(denominator) + \" is \" + str(result))\n","except ValueError:\n","    print(\"Please enter valid numbers for the numerator and denominator.\")\n","except ZeroDivisionError:\n","    print(\"The denominator cannot be zero.\")\n","except Exception as e:\n","    print(\"An error occurred:\", e)"],"metadata":{"id":"YneuFASstC8K","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1681787460999,"user_tz":360,"elapsed":2209,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"fb06735e-f45a-4f53-db83-3a80b9d55d0e"},"execution_count":10,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter the numerator: a\n","Enter the denominator: 6\n","Please enter valid numbers for the numerator and denominator.\n"]}]},{"cell_type":"markdown","source":["## Try Except Else\n","\n","The `try` block contains the code that may cause an exception to be raised. If an exception occurs, the `except` block is executed, and the program can handle the exception in a way that is appropriate for the situation.\n","\n","However, if no exception is raised, the `else` block is executed. The `else` block is optional and is executed when the `try` block does not raise any exception.\n","\n","<br>\n","\n","### **Implementation**\n","\n","```python\n","  try:\n","    # Code that might raise an exception\n","  except ExceptionType1:\n","      # Code that handles ExceptionType1\n","  except ExceptionType2:\n","      # Code that handles ExceptionType2\n","  else:\n","      # Code that executes when there is no exception raised\n","```\n","\n","<br>\n","\n","#### Code examples"],"metadata":{"id":"TUXcopz-tf3F"}},{"cell_type":"code","source":["try:\n","    num1 = int(input(\"Enter a numerator: \"))\n","    num2 = int(input(\"Enter a denominator: \"))\n","    result = num1 / num2\n","except ZeroDivisionError:\n","    # Exist an error\n","    print(\"Error: Cannot divide by zero!\")\n","else:\n","    # Only executed when there is no error\n","    print(\"Result: \", result)"],"metadata":{"id":"ySe279OmulhC","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1681787768350,"user_tz":360,"elapsed":3342,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"f511cc5e-1686-4e2c-e08f-1e69e5e933f1"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter a numerator: 2\n","Enter a denominator: 1\n","Result:  2.0\n"]}]},{"cell_type":"code","source":["try:\n","    num1 = int(input(\"Enter a numerator: \"))\n","    num2 = int(input(\"Enter a denominator: \"))\n","    result = num1 / num2\n","    print(\"Result: \", result)\n","except ZeroDivisionError:\n","    # Exist an error\n","    print(\"Error: Cannot divide by zero!\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"61LuBXAQXVFU","executionInfo":{"status":"ok","timestamp":1681787814572,"user_tz":360,"elapsed":5617,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"b9dc1c5b-c82e-48eb-936d-dc7ca3fdc30a"},"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["Enter a numerator: 2\n","Enter a denominator: 1\n","Result:  2.0\n"]}]},{"cell_type":"markdown","source":["## Try Except Finally\n","\n","\n","`finally` block: This is the block of code that will always be executed, regardless of whether an exception was raised or not. The code in the `finally` block is useful for releasing resources, closing files, or performing other cleanup tasks.\n","\n","<br>\n","\n","### **Implementation**\n","\n","```python\n","  try:\n","      # code that may raise an exception\n","  except ExceptionType:\n","      # code to handle the exception\n","  finally:\n","      # code that will always execute, regardless of whether an exception was raised or not\n","```\n","\n","<br>\n","\n","#### Code examples\n"],"metadata":{"id":"UReQbbSLzp3v"}},{"cell_type":"code","source":["try:\n","    num1 = int(input(\"Enter a numerator: \"))\n","    num2 = int(input(\"Enter a denominator: \"))\n","    result = num1 / num2\n","    print(\"Result: \", result)\n","except ZeroDivisionError:\n","    # Exist an error\n","    print(\"Error: Cannot divide by zero!\")\n","finally:\n","    # Always executed\n","    print(\"The program is finished, cleaning variables...\")\n","    num1 = None\n","    num2 = None\n","    result = None"],"metadata":{"id":"p6OqivEkzqOU"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["## <font color='#8DB580'>***Raise exception***</font>\n","\n","Raising an exception means that we want to interrupt the normal flow of the program and report an error condition to the caller or to the user.\n","\n","The `raise` statement can be used with or without an argument. If no argument is provided, it simply re-raises the last exception that occurred in the program. If an argument is provided, it should be an instance of an exception class, which can be a built-in exception or a custom exception that we defined.\n","\n","<br>\n","\n","#### Examples:\n","```python\n","  x = -1\n","\n","  if x < 0:\n","      raise ValueError(\"x cannot be negative\")\n","```\n","\n","<br>\n","\n","#### Code example"],"metadata":{"id":"jvv2eyn51BWD"}},{"cell_type":"code","source":["x = -1\n","\n","try:\n","  if x < 0:\n","      raise ValueError(\"x cannot be negative\")\n","  print(x)\n","except Exception as e:\n","  print(e)"],"metadata":{"id":"CZzJvGX417pe","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1681789466077,"user_tz":360,"elapsed":208,"user":{"displayName":"Andrei noguera gil","userId":"00676865675105879181"}},"outputId":"feb8c41e-70ac-4e33-beda-c0374ae39b30"},"execution_count":25,"outputs":[{"output_type":"stream","name":"stdout","text":["-1\n"]}]},{"cell_type":"markdown","source":["___\n","___\n","## <font color='#8DB580'>***Tips***</font>\n","\n","1. Be specific with the exception types you catch. Catching a broad exception like `Exception` may hide underlying issues and make it harder to debug your code. Instead, catch only the exceptions you expect to occur.\n","\n","1. Use `try-except` blocks only when you expect an exception to occur. If the exception is not expected, it is better to let the program crash and raise an error that you can debug and fix.\n","\n","1. Avoid using bare `except` blocks. Instead, catch specific exceptions or create custom exception classes.\n","\n","1. Don't suppress exceptions. If an exception occurs, handle it appropriately or let it propagate up the call stack.\n","\n","1. Use the `finally` block for cleanup code that should be executed regardless of whether an exception is thrown or not.\n","\n","1. Don't ignore error messages. They provide important information that can help you diagnose and fix the problem.\n","\n","1. Log exceptions instead of printing them to the console. This can be more useful for debugging, and allows you to track exceptions over time.\n","\n","1. Use `with` statements for resources that need to be cleaned up, such as file objects or network connections. This ensures that the resource is properly closed, even if an exception occurs.\n","\n","1. Avoid catching `KeyboardInterrupt` exceptions, which are raised when the user presses Ctrl-C. Letting these exceptions propagate up the call stack allows the program to be gracefully terminated.\n","\n","1. Test your exception handling code thoroughly to ensure it works as expected, and consider edge cases where unexpected exceptions may occur."],"metadata":{"id":"Y2h3LW7g1GF7"}}]}